spring.application.name=fare-payment-service
server.port=${SERVER_PORT:8084}

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_fare_payment

# JWT
security.jwt.secret=${JWT_SECRET:RideLinkDemoSecretKey-ChangeThis-AtLeast32Chars}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs