# Local developer profile overrides
server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ride_management_db

services:
  driver-vehicle:
    base-url: http://localhost:8082
  fare-payment:
    base-url: http://localhost:8084

logging:
  level:
    com.ridelink.ridemanagement: DEBUG
